FROM node:24-slim

RUN corepack enable && corepack prepare pnpm@10.34.5 --activate
RUN ldd --version
RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN pnpm install --frozen-lockfile \
    && pnpm --filter DeepChat run installRuntime:linux:x64 \
    && pnpm --filter DeepChat run install:sharp

CMD ["pnpm", "--filter", "DeepChat", "run", "build:linux:x64"]
